contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #alphafold channel"
    url: https://nfcore.slack.com/channels/alphafold
    about: Discussion about the nf-core/alphafold pipeline
